# 01
par_species: 'mouse' # mouse or human
par_data_dir: 'example-data'
par_initial_umi_cutoff: 10
par_initial_gene_cutoff: 10

# EmptyDrops
par_empty_drops_lower_umi_cutoff: 200
par_empty_drops_ignore_cutoff: 10
par_empty_drops_niters: 10000
par_empty_drops_fdr_cutoff: 0.01
par_empty_drops_retain: 800

## 02A
par_cutoff_min_counts: 200
par_cutoff_min_genes : 200
par_cutoff_max_genes : null
par_final_empty_drops_fdr_cutoff: 0.01
par_remove_mito_genes: True
par_mito_cutoff: 0.0
par_remove_sex_genes: False
par_preprocessing_target_sum: 10000
par_regress_out_variables: []
par_regress_out_n_jobs: 1

# downstream parameters
par_downstream_n_top_genes: 2000
par_downstream_n_pcs: 50
par_downstream_n_neighbors: 15
par_downstream_louvain_resolution: 1.5
par_downstream_neighbor_metric: 'euclidean'
par_save_filename_sample: 'adata-sample-%s.h5ad'

## 02B
par_save_filename: 'adata.h5ad'
par_save_filename_group: 'adata-group-%s.h5ad'
par_remove_doublets: True
par_generate_plots_per_group: True
par_group_key: 'tissue'
par_merge_type: 'inner'
par_batch_key: 'sample_name'

## 03
par_de_group: 'leiden'
par_de_n_genes: 2000
par_de_method: 't-test_overestim_var'
par_per_group_de: True
par_group_key: 'tissue'
par_save_filename_de: 'de-genes.xlsx'
par_save_filename_de_group: 'de-genes-%s.xlsx'
